---
title: "TidyTuesday Friends"
output: html_document
---
TidyTuesday Friends 2020-09-08 |
[Description](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-08/readme.md) |
Contributor: Sabina Rako, Twitter: @ra_sabina]

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidytuesdayR)
library(tidyverse)
library(skimr)
library(ggplot2)
library(forcats)
library(ggthemes)
library(lubridate)
library(mdthemes)
library(patchwork)
```

## Loading data

```{r message=FALSE, warning=FALSE}
#tuesdata <- tidytuesdayR::tt_load('2020-09-08')
#friends <- tuesdata$friends
friends_info <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-08/friends_info.csv')
```

## Exploring data

```{r message=FALSE, warning=FALSE}
#skim(friends)
skim(friends_info)
```

## Preparing data 
- number of episodes per month

```{r message=FALSE, warning=FALSE}
# changing variable air_date (Date) 
friends_info$air_date <- lubridate::ymd(friends_info$air_date)

episodesmonth <- table(lubridate::month(friends_info$air_date, label = TRUE)) %>% 
  as.data.frame() %>% 
  dplyr::rename(Month = Var1)
```

## First visualization
- number of episodes per month

```{r vis1, message=FALSE, warning=FALSE}
p1 <- ggplot(episodesmonth, aes(Month, Freq)) +
  geom_segment( aes(x = Month, xend = Month, y = 0, yend = Freq)) +
  geom_point(size = 9) + scale_y_continuous(breaks = seq(0, 40, 10), limits=c(-1,45)) +  
  mdthemes::md_theme_fivethirtyeight() + 
  theme(panel.grid.major.x = element_blank() ) + 
  labs(title = "Number of <span style=color:#ff4747>**Friends**</span> episodes per month") + ylab("Number of episodes")
    

p1 <- p1 + 
  annotate(geom = "text",
           x  = episodesmonth$Month, 
           y = episodesmonth$Freq, 
           label = episodesmonth$Freq, 
           size = 4, color = "white", 
           fontface = "bold") + 
  annotate(geom = "text", 
           x = episodesmonth$Month[episodesmonth$Freq== max(episodesmonth$Freq)], 
           y = max(episodesmonth$Freq), 
           label = max(episodesmonth$Freq), 
           size = 4, 
           color = "#ff4747", 
           fontface = "bold") + 
  annotate("text", 
           label = "Friends episodes were mostly \naired during October", 
           x = "Jul", 
           y = 37) + 
  geom_curve(x ="Aug", 
             y = 40, 
             xend = "Oct", 
             yend = 40,  
             curvature = -.5, 
             arrow = arrow(length = unit(2, "mm")))

p1
```

## Preparing data
- IMDB ratings per month

```{r message=FALSE, warning=FALSE}
ratingsmonth <-  friends_info %>% 
  mutate( month = lubridate::month(air_date, label = TRUE)) %>% 
  select(month, imdb_rating)  %>% 
  add_row(month = "Jun", imdb_rating = NULL) %>% 
  add_row(month = "Jul", imdb_rating = NULL) %>% 
  add_row(month = "Aug", imdb_rating = NULL) 

month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
```

## Second visualization
- IMDB ratings per month

```{r vis2, message=FALSE, warning=FALSE}

p2 <- ggplot(ratingsmonth, aes(factor(month, levels = month_levels), y=imdb_rating)) + 
  geom_violin(trim = FALSE, fill = "#ff4747") + 
  scale_y_continuous(breaks = seq(6.5, 10.5, 1), limits=c(6,11)) +  
  mdthemes::md_theme_fivethirtyeight() + 
  theme(panel.grid.major.x = element_blank()) + 
  labs(title = "<span style=color:#ff4747>**Friends**</span> IMDB ratings per month") + 
  xlab("Month") + 
  ylab("IMDB rating")

p2 <- p2  + 
  annotate("text",
    label = "'The One with Ross's Sandwich' episode was rated \nhigher then the other episodes aired during December", 
    x = "Jul", y = 10.6) + 
  geom_curve(x ="Nov", 
    y = 10.5, 
    xend = "Dec", 
    yend = 9.4,  
    curvature = -.5, 
    arrow = arrow(length = unit(2, "mm")))

p2

```

## Combining and saving plot

```{r combined, fig.height=6, fig.width=14, message=FALSE, warning=FALSE}
p1 + p2 + 
  labs(caption = "Data source: ceros interactive article & Emil Hvitfeldt Vis: @ra_sabina")
```


```{r final, message=FALSE, warning=FALSE}
ggsave("PlotTTw37.png",  dpi = 700, width = 14)

```

